#!/usr/bin/env python
"""Three-row Ac-Pro-NHMe landscape: KLXX, KLXX reweighted to raw, reference.

Row 1 is the final KLXX stage.  Row 2 applies the endpoint-to-physical
correction: the same samples are reweighted from the regularized target to the
raw physical potential by the regularization ESS (RESS) weights, resampled, and
rejuvenated with mixed-domain MALA under that potential.  Row 3 is the OpenMM
parallel-tempering reference generated by ``reference/pt_reference.py`` and
extended by ``reference/langevin_extend.py``.

The comparison isolates whether that correction step changes the landscape.
The log-weight convention follows ``Codes/Molecular_BG/alkane_family/
regularization_ess.py``: ``log w = U_regularized(q) - U_raw(q)``.

Panel conventions are taken from the sibling ``plot_conformational_landscape.py``
so all three rows are built identically.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path


os.environ.setdefault("XLA_PYTHON_CLIENT_PREALLOCATE", "false")

import equinox as eqx
import jax
import jax.numpy as jnp
import matplotlib


matplotlib.use("Agg")

from matplotlib import pyplot as plt
import numpy as np

from jflows.utils import compute_ESS_log
from jflows_md import Molecular_Potential
from jflows_md.boltzmann.load import load_validation_samples, validate_run
from jflows_md.utils import mixed_mala

from parameters import CHUNKS, MC_DT, MC_IMAGE_RADIUS, MC_STEPS, RG_PARAM_1
from plot_conformational_landscape import (
    BUNDLE,
    CHI1_ATOMS,
    FREE_ENERGY_CMAP,
    OMEGA_ATOMS,
    PHI_ATOMS,
    PSI_ATOMS,
    RUN_DIR,
    dihedral,
    free_energy,
    histograms,
    occupied_y_limits,
)


HERE = Path(__file__).resolve().parent
REFERENCE = HERE / "reference" / "pt_reference_frames.npz"
DEFAULT_OUTPUT = HERE / "results" / "conformational_landscape_reference_v2.png"
DEFAULT_REPORT = HERE / "results" / "landscape_reference_comparison.md"
SEED = 0
VMAX = 9.0

# Regions are classified by the OpenMM reference surface, so every method is
# scored on the same bins.
LOW_FREE_ENERGY = 2.0
HIGH_FREE_ENERGY = 3.0


@eqx.filter_jit
def log_weight(samples, regularized, exact):
    return regularized(samples) - exact(samples)


def final_stage(run_dir: Path) -> tuple[dict, np.ndarray]:
    """Load the persisted final KLXX stage at t=1."""

    record = validate_run(run_dir)
    stages = record.get("stages", [])
    if record.get("status") != "complete" or not stages:
        raise ValueError("KLXX run is not complete")
    stage_ref = stages[-1]
    if not math.isclose(float(stage_ref["t"]), 1.0, abs_tol=1e-12):
        raise ValueError(f"final stage has t={stage_ref['t']}, not t=1")
    stage_number = int(stage_ref["stage"])
    stage_root = (run_dir / stage_ref["path"]).resolve()
    try:
        stage_root.relative_to(run_dir.resolve())
    except ValueError as error:
        raise ValueError(f"stage path escapes run directory: {stage_root}") from error
    metadata = json.loads((stage_root / "stage.json").read_text(encoding="utf-8"))
    samples = load_validation_samples(run_dir, stage_number, mmap_mode="r")
    if samples.ndim != 2 or samples.dtype != np.float32:
        raise ValueError(
            f"expected a float32 sample matrix, found {samples.shape} {samples.dtype}"
        )
    return metadata, samples


def reference_histograms(
    positions: np.ndarray, bins: int
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Histogram the reference torsions on the same grid as the KLXX samples."""

    edges = np.linspace(-np.pi, np.pi, bins + 1)
    phi = dihedral(positions, PHI_ATOMS)
    psi = dihedral(positions, PSI_ATOMS)
    omega = dihedral(positions, OMEGA_ATOMS)
    chi1 = dihedral(positions, CHI1_ATOMS)
    backbone = np.histogram2d(phi, psi, bins=(edges, edges))[0].astype(np.int64)
    peptide_ring = np.histogram2d(omega, chi1, bins=(edges, edges))[0].astype(np.int64)
    frames = positions.shape[0]
    if int(backbone.sum()) != frames or int(peptide_ring.sum()) != frames:
        raise ValueError("a reference histogram dropped frames")
    return edges, backbone, peptide_ring


def reweighted_samples(
    samples: np.ndarray, target: Molecular_Potential, chunks: int
) -> tuple[np.ndarray, float, float]:
    """Resample by RESS weights and rejuvenate under the raw potential."""

    regularized = target.regularized(RG_PARAM_1)
    parts = []
    for part in np.array_split(np.asarray(samples), chunks, axis=0):
        parts.append(
            np.asarray(
                jax.block_until_ready(
                    log_weight(jnp.asarray(part), regularized, target)
                )
            )
        )
    weights = np.concatenate(parts)
    ess = float(jax.block_until_ready(compute_ESS_log(jnp.asarray(weights))))

    probabilities = np.exp(weights - weights.max())
    probabilities /= probabilities.sum()
    generator = np.random.default_rng(SEED)
    index = generator.choice(
        weights.size, size=weights.size, replace=True, p=probabilities
    )
    resampled = jnp.asarray(np.asarray(samples)[np.sort(index)])

    rejuvenated, acceptance = mixed_mala(
        jax.random.key(SEED),
        resampled,
        target,
        target.domain,
        dt=MC_DT,
        steps=MC_STEPS,
        image_radius=MC_IMAGE_RADIUS,
        chunks=chunks,
    )
    # ``mixed_mala`` returns the per-step acceptance history; report its mean.
    return np.asarray(rejuvenated), ess, float(np.asarray(acceptance).mean())


def cis_trans_pucker(counts: np.ndarray, edges: np.ndarray) -> tuple[float, ...]:
    """Return trans/cis fractions of the omega marginal of a 2D histogram."""

    marginal = counts.sum(axis=1).astype(np.float64)
    centers = 0.5 * (edges[:-1] + edges[1:])
    trans = np.abs(centers) > np.pi / 2.0
    total = marginal.sum()
    return float(marginal[trans].sum() / total), float(marginal[~trans].sum() / total)


def write_report(
    path: Path, edges, panels: dict, counts: dict, ress: float, acceptance: float
) -> None:
    """Write the three-way raw free-energy comparison table."""

    names = ("KLXX", "KLXX resampled + rejuvenated", "OpenMM reference")
    lines = [
        "# Ac-Pro-NHMe landscape comparison",
        "",
        "Three sample sets on the same 100-bin torsion grid with the same",
        "wrapped smoothing, each surface normalized to its own most populated",
        "bin. `KLXX resampled + rejuvenated` is the KLXX set reweighted by the",
        "regularization ESS weights, resampled, then rejuvenated with",
        "mixed-domain MALA under the raw potential.",
        "",
        f"- Regularization ESS (RESS): `{ress:.6f}`",
        f"- Mixed-domain MALA acceptance during rejuvenation: `{acceptance:.4f}`",
        "",
        "## Surface extent",
        "",
        "| diagnostic | sample set | occupied bins | max free energy / kBT |",
        "|---|---|---:|---:|",
    ]
    for diagnostic in ("backbone", "peptide/ring"):
        for name in names:
            surface = panels[diagnostic][name]
            finite = surface[np.isfinite(surface)]
            lines.append(
                f"| {diagnostic} | {name} | {int((counts[diagnostic][name] > 0).sum())}"
                f" | {float(finite.max()):.2f} |"
            )
    lines += [
        "",
        "## Free energy by region",
        "",
        "Bins are classified by the OpenMM reference: low means below "
        f"{LOW_FREE_ENERGY:.0f} kBT, high means above {HIGH_FREE_ENERGY:.0f} kBT.",
        "Entries are the mean free energy of each set over those bins, in kBT.",
        "Only bins finite in all three surfaces are used, so the rows are",
        "directly comparable.",
        "",
        "| diagnostic | region | bins | " + " | ".join(names) + " |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for diagnostic in ("backbone", "peptide/ring"):
        here = [panels[diagnostic][name] for name in names]
        finite = np.logical_and.reduce([np.isfinite(s) for s in here])
        reference = panels[diagnostic]["OpenMM reference"]
        for label, mask in (
            (f"low F (< {LOW_FREE_ENERGY:.0f} kBT)", finite & (reference < LOW_FREE_ENERGY)),
            (f"high F (> {HIGH_FREE_ENERGY:.0f} kBT)", finite & (reference > HIGH_FREE_ENERGY)),
            ("all bins", finite),
        ):
            values = " | ".join(
                f"{panels[diagnostic][name][mask].mean():.3f}" for name in names
            )
            lines.append(f"| {diagnostic} | {label} | {int(mask.sum())} | {values} |")

    lines += [
        "",
        "## ACE-PRO peptide torsion populations",
        "",
        "| sample set | trans | cis |",
        "|---|---:|---:|",
    ]
    for name in names:
        trans, cis = cis_trans_pucker(counts["peptide/ring"][name], edges)
        lines.append(f"| {name} | {trans:.4f} | {cis:.4f} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", type=Path, default=RUN_DIR)
    parser.add_argument("--reference", type=Path, default=REFERENCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--bins", type=int, default=100)
    parser.add_argument("--smoothing", type=float, default=1.2)
    parser.add_argument("--chunk-size", type=int, default=20_000)
    args = parser.parse_args()
    if args.bins <= 0 or args.smoothing < 0.0 or args.chunk_size <= 0:
        parser.error("bins and chunk size must be positive; smoothing nonnegative")

    output = args.output.expanduser().resolve()
    target = Molecular_Potential.from_bundle(BUNDLE, temperature_kelvin=300.0)

    with np.load(args.reference.expanduser().resolve()) as handle:
        positions = np.asarray(handle["positions_nm"], dtype=np.float64)
    atoms = (target.dimension + 6) // 3
    if positions.ndim != 3 or positions.shape[1:] != (atoms, 3):
        raise ValueError(
            f"expected reference frames [F, {atoms}, 3], found {positions.shape}"
        )
    edges, reference_backbone, reference_ring = reference_histograms(
        positions, args.bins
    )
    print(f"reference frames={positions.shape[0]:,}", flush=True)

    metadata, samples = final_stage(args.run_dir.expanduser().resolve())
    if target.dimension != samples.shape[1] or samples.shape[1] != 72:
        raise ValueError(
            f"unexpected dimension: target={target.dimension}, samples={samples.shape}"
        )
    klxx_edges, klxx_backbone, klxx_ring, _ = histograms(
        samples, target, args.bins, args.chunk_size
    )
    if not np.allclose(edges, klxx_edges):
        raise ValueError("KLXX and reference histograms use different edges")
    print(
        f"klxx stage={int(metadata['stage'])} samples={samples.shape[0]:,}",
        flush=True,
    )

    corrected, ress, acceptance = reweighted_samples(samples, target, CHUNKS)
    _, corrected_backbone, corrected_ring, _ = histograms(
        corrected, target, args.bins, args.chunk_size
    )
    print(
        f"corrected samples={corrected.shape[0]:,} RESS={ress:.6g} "
        f"mala_acceptance={acceptance:.4f}",
        flush=True,
    )

    rows = (
        (
            (
                rf"KLXX stage {int(metadata['stage'])}",
                rf"$t={float(metadata['t']):.3f}$, "
                rf"$\rho=({float(metadata['rg_end'][0]):.3g},"
                rf"{float(metadata['rg_end'][1]):.3g})$",
            ),
            (klxx_backbone, klxx_ring),
        ),
        (
            ("KLXX resampled + rejuvenated", rf"unregularized, RESS $={ress:.4f}$"),
            (corrected_backbone, corrected_ring),
        ),
        (
            ("OpenMM reference", r"unregularized, $300$ K"),
            (reference_backbone, reference_ring),
        ),
    )
    surfaces = [
        (labels, tuple(free_energy(counts, args.smoothing) for counts in pair), pair)
        for labels, pair in rows
    ]

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Computer Modern Roman", "DejaVu Serif"],
            "mathtext.fontset": "cm",
            "font.size": 13,
            "axes.titlesize": 14,
            "axes.labelsize": 15,
            "xtick.labelsize": 13,
            "ytick.labelsize": 13,
        }
    )
    figure, axes = plt.subplots(3, 2, figsize=(9.8, 13.2), layout="constrained")
    figure.get_layout_engine().set(wspace=0.0, w_pad=0.01)
    panel_letters = ("a", "b", "c", "d", "e", "f")
    # One pucker window shared by every row keeps the three panels comparable.
    pucker_ylim = occupied_y_limits(reference_ring, edges)
    image = None
    for row, ((heading, subheading), pair, _) in enumerate(surfaces):
        left = axes[row, 0]
        image = left.pcolormesh(
            edges, edges, pair[0].T, cmap=FREE_ENERGY_CMAP,
            vmin=0.0, vmax=VMAX, shading="flat", rasterized=True,
        )
        left.set(
            xlim=(-np.pi, np.pi),
            ylim=(-np.pi, np.pi),
            xlabel=r"proline $\phi$ (rad)",
            ylabel=r"proline $\psi$ (rad)",
            title=f"({panel_letters[2 * row]}) {heading}\n{subheading}",
        )
        left.set_aspect("equal")
        left.set_box_aspect(1)
        left.set_xticks((-np.pi, 0.0, np.pi), (r"$-\pi$", "0", r"$\pi$"))
        left.set_yticks((-np.pi, 0.0, np.pi), (r"$-\pi$", "0", r"$\pi$"))

        right = axes[row, 1]
        right.pcolormesh(
            edges, edges, pair[1].T, cmap=FREE_ENERGY_CMAP,
            vmin=0.0, vmax=VMAX, shading="flat", rasterized=True,
        )
        right.set(
            xlim=(-np.pi, np.pi),
            ylim=pucker_ylim,
            xlabel=r"ACE-PRO $\omega$ (rad)",
            ylabel=r"proline-ring $\chi_1$ (rad)",
            title=f"({panel_letters[2 * row + 1]}) {heading}\n{subheading}",
        )
        right.set_xticks(
            (-np.pi, -np.pi / 2.0, 0.0, np.pi / 2.0, np.pi),
            (r"$-\pi$", r"$-\pi/2$", "0", r"$\pi/2$", r"$\pi$"),
        )
        right.set_box_aspect(1)
        right.axvline(-np.pi / 2.0, color="white", lw=0.9, ls="--")
        right.axvline(np.pi / 2.0, color="white", lw=0.9, ls="--")
        right.axhline(0.0, color="black", lw=0.9, ls=":")
        label_y = pucker_ylim[1] - 0.04 * (pucker_ylim[1] - pucker_ylim[0])
        right.text(0.0, label_y, "cis", ha="center", va="top", color="#222222")
        right.text(-2.45, label_y, "trans", ha="center", va="top", color="#222222")
        right.text(2.45, label_y, "trans", ha="center", va="top", color="#222222")

        for axis in axes[row]:
            for spine in axis.spines.values():
                spine.set_linewidth(1.0)

    colorbar = figure.colorbar(
        image, ax=axes, pad=0.012, fraction=0.032, shrink=0.95
    )
    colorbar.set_ticks(np.arange(0.0, VMAX + 0.1, 2.0))
    colorbar.set_label(r"free energy / $k_{\mathrm{B}}T$")

    figure.suptitle("N-acetyl-L-proline N-methylamide", fontsize=16)
    output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output, dpi=300, bbox_inches="tight")
    plt.close(figure)

    names = ("KLXX", "KLXX resampled + rejuvenated", "OpenMM reference")
    panels = {
        "backbone": {name: surfaces[i][1][0] for i, name in enumerate(names)},
        "peptide/ring": {name: surfaces[i][1][1] for i, name in enumerate(names)},
    }
    counts = {
        "backbone": {name: surfaces[i][2][0] for i, name in enumerate(names)},
        "peptide/ring": {name: surfaces[i][2][1] for i, name in enumerate(names)},
    }
    write_report(
        args.report.expanduser().resolve(), edges, panels, counts, ress, acceptance
    )
    print(
        f"backend={jax.default_backend()} output={output} report={args.report}",
        flush=True,
    )


if __name__ == "__main__":
    main()
