import json
import math
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "tables.md"
REGULARIZATION_ESS = ROOT / "regularization_ess.json"
MACROSCOPIC = ROOT / "macroscopic.json"
METHOD_ORDER = {"ID": 0, "KL": 1, "KLXX": 2}


def number(value):
    return f"{value:.6g}"


def scientific(value):
    if value == 0:
        return "0"
    mantissa, exponent = f"{value:.1e}".split("e")
    return f"{mantissa}e{int(exponent)}"


def duration(seconds):
    return f"{seconds / 60:.1f}min"


def uses_sharpening(stage):
    return stage["rg_start"] != stage["rg_end"]


def collect():
    runs = []
    for molecule_dir in ROOT.iterdir():
        match = re.fullmatch(
            r"(.+)_([0-9]+)d(?:_(?:raw|sharpening))?",
            molecule_dir.name,
        )
        if not match:
            continue
        molecule = match.group(1).replace("_", " ").title()
        dimension = int(match.group(2))
        for run_file in (molecule_dir / "artifacts").glob("*/run.json"):
            run = json.loads(run_file.read_text())
            if run["status"] != "complete":
                continue
            method = run["config"].get("method", run_file.parent.name)
            stages = []
            for stage_file in run_file.parent.glob("stages/stage_*/stage.json"):
                stages.append(json.loads(stage_file.read_text()))
            stages.sort(key=lambda stage: stage["stage"])
            if stages:
                runs.append({
                    "molecule": molecule,
                    "dimension": dimension,
                    "variant": (
                        "Sharpening" if any(uses_sharpening(stage) for stage in stages)
                        else "Raw"
                    ),
                    "method": method.upper(),
                    "stages": stages,
                })
    return sorted(
        runs,
        key=lambda run: (
            run["dimension"],
            run["variant"] == "Sharpening",
            METHOD_ORDER[run["method"]],
        ),
    )


def steps(stages):
    """Reweighting steps of one run, in the order the generator performs them.

    Each accepted stage reweights and resamples twice: first on the selected
    flow or identity proposal, then on the sharpening weight. The second step
    is taken on every accepted stage, so it is listed even where the
    regularization path is fixed and its ESS is one.
    """
    for stage in stages:
        yield "selected", stage["valid_selected_ess"]
        yield "sharpening", stage["sharpen_ess"]


def factor(stages):
    """Propagation factor ``sum_k prod_{j>k} ESS_j**(-1/2)`` over the steps.

    Accumulated from the last step backwards, so the running product carries
    the suffix ``prod_{j=k+1}^{K}`` and the ``k = K`` summand is the empty
    product. Every summand is at least one, hence the factor is at least the
    number of steps plus one.
    """
    total = 1.0
    suffix = 1.0
    for _, ess in reversed(list(steps(stages))):
        suffix /= math.sqrt(ess)
        total += suffix
    return total


def build(runs):
    regularization_ess = (
        json.loads(REGULARIZATION_ESS.read_text())
        if REGULARIZATION_ESS.exists() else {}
    )
    macroscopic = (
        json.loads(MACROSCOPIC.read_text()) if MACROSCOPIC.exists() else {}
    )
    lines = [
        "# Alkane-family ESS tables",
        "",
        "Generated by `python build_table.py` from the accepted-stage metadata in "
        "each molecule's `artifacts` directory.",
        "",
        "Each accepted stage reweights and resamples twice, first on the "
        "selected flow or identity proposal and then on the sharpening "
        "weight, so a run of $K$ accepted stages performs $2K$ steps. The "
        "total factor is",
        "",
        r"$$\sum_{k=0}^{2K} \prod_{j=k+1}^{2K} "
        r"\operatorname{ESS}_j^{-1/2},$$",
        "",
        "with the empty product equal to one, the steps indexed in the order "
        "the generator performs them. The sharpening step is charged on every "
        "accepted stage, because the generator resamples there whether or not "
        "the regularization path moves; on a fixed path its ESS is one and it "
        "contributes a summand but no growth. Every summand is at least one, "
        "so the factor is at least $2K+1$.",
        "",
        "The molecule-level `1-RESS` is the ESS deficit when reweighting the "
        "final KLXX samples at `(100, 0.15)` toward the exact, "
        "unregularized molecular potential.",
        "",
        "## Summary",
        "",
        '<div align="left">',
        "",
        "<table>",
        "<thead>",
        "<tr><th>molecule</th><th>regularization</th><th>method</th><th>stages</th>"
        "<th>total factor</th><th>total time</th></tr>",
        "</thead>",
        "<tbody>",
    ]
    molecule_groups = {}
    variant_groups = {}
    methods = {}
    best_total = {}
    for run in runs:
        molecule_key = (run["molecule"], run["dimension"])
        variant_key = (*molecule_key, run["variant"])
        molecule_groups[molecule_key] = molecule_groups.get(molecule_key, 0) + 1
        variant_groups[variant_key] = variant_groups.get(variant_key, 0) + 1
        methods.setdefault(variant_key, set()).add(run["method"])
        if run["method"] in ("KL", "KLXX"):
            total = factor(run["stages"])
            best_total[variant_key] = min(
                best_total.get(variant_key, total), total
            )
    current_summary = None
    current_variant = None
    for run in runs:
        key = (run["molecule"], run["dimension"])
        variant_key = (*key, run["variant"])
        total = factor(run["stages"])
        total_text = number(total)
        if (
            run["method"] in ("KL", "KLXX")
            and methods[variant_key] >= {"KL", "KLXX"}
            and total == best_total[variant_key]
        ):
            total_text = f"<strong>{total_text}</strong>"
        molecule = ""
        if key != current_summary:
            ress = regularization_ess.get(str(run["dimension"]), {}).get("ess")
            ress_text = (
                scientific(max(0.0, 1.0 - ress))
                if ress is not None else "pending"
            )
            molecule = (
                f'<td rowspan="{molecule_groups[key]}">'
                f"{run['molecule'].lower()} ({run['dimension']}d)<br>"
                f"1-ress={ress_text}</td>"
            )
            current_summary = key
        variant = ""
        if variant_key != current_variant:
            variant = (
                f'<td rowspan="{variant_groups[variant_key]}">'
                f"{run['variant'].lower()}</td>"
            )
            current_variant = variant_key
        lines.append(
            f"<tr>{molecule}{variant}<td>{run['method'].lower()}</td>"
            f"<td>{len(run['stages'])}</td><td>{total_text}</td>"
            f"<td>{duration(sum(stage['elapsed_seconds'] for stage in run['stages']))}</td>"
            "</tr>"
        )
    if not runs:
        lines.append('<tr><td colspan="6">no completed stages found.</td></tr>')
    lines.extend([
        "</tbody>",
        "</table>",
        "",
        "</div>",
    ])

    if macroscopic:
        lines.extend([
            "",
            "## Direct KLXX macroscopic observables",
            "",
            "These are unweighted sample statistics from the best completed "
            "KLXX final validation set for each molecule at "
            "`rg_param = (100, 0.15)`. No RESS resampling or reweighting is "
            "applied. The physical energy is evaluated under the raw, "
            "unregularized potential. Continuous quantities in the table are "
            "reported as mean ± thermal/sample standard deviation. `R_g,C` is "
            "the carbon-skeleton radius of gyration and "
            "`R_ee,C` is the terminal-carbon distance. Rotamer populations are "
            "pooled over all backbone C–C–C–C dihedrals, using trans when "
            "`|φ| ≥ 2π/3`.",
            "",
            "The independent benchmark uses the native OpenMM backend on the "
            "raw potential with a 0.25 fs timestep and two seeds. Methane "
            "through propane use 300 K Langevin trajectories; butane through "
            "hexane use 300–800 K replica exchange to mix backbone rotamers. "
            "OpenMM error bars on continuous observables span the two seed "
            "means rather than treating correlated frames as independent; "
            "the rotamer bars pool both seeds. The comparison supports "
            "consistent energy and carbon-skeleton growth across the C1–C6 "
            "homologous series and agreement on the selected observables; it "
            "does not assert equality of the full distributions.",
            "",
            '<p align="center"><img src="results/macroscopic.png" '
            'alt="KLXX macroscopic scaling across the alkane family" '
            'width="1000px"></p>',
            "",
            '<div align="left">',
            "",
            "<table>",
            "<thead>",
            "<tr><th>molecule</th><th>benchmark</th><th>n</th>"
            "<th>energy (kj/mol)</th>"
            "<th>r<sub>g,c</sub> (nm)</th><th>r<sub>ee,c</sub> (nm)</th>"
            "<th>backbone φ</th><th>trans</th><th>gauche+</th>"
            "<th>gauche−</th></tr>",
            "</thead>",
            "<tbody>",
        ])
        for dimension in sorted(int(value) for value in macroscopic):
            record = macroscopic[str(dimension)]
            if record["backbone_torsion_count"]:
                populations = (
                    f"{record['trans_fraction']:.3f}",
                    f"{record['gauche_plus_fraction']:.3f}",
                    f"{record['gauche_minus_fraction']:.3f}",
                )
            else:
                populations = ("—", "—", "—")
            lines.append(
                f"<tr><td>{record['molecule'].lower()} ({dimension}d)</td>"
                f"<td>{record['benchmark'].lower()}</td><td>{record['sample_count']}</td>"
                f"<td>{record['physical_energy_mean_kj_mol']:.1f} ± "
                f"{record['physical_energy_sd_kj_mol']:.1f}</td>"
                f"<td>{record['carbon_radius_mean_nm']:.4f} ± "
                f"{record['carbon_radius_sd_nm']:.4f}</td>"
                f"<td>{record['carbon_end_to_end_mean_nm']:.4f} ± "
                f"{record['carbon_end_to_end_sd_nm']:.4f}</td>"
                f"<td>{record['backbone_torsion_count']}</td>"
                f"<td>{populations[0]}</td><td>{populations[1]}</td>"
                f"<td>{populations[2]}</td></tr>"
            )
        lines.extend([
            "</tbody>",
            "</table>",
            "",
            "</div>",
        ])

    current_molecule = None
    for run in runs:
        if run["molecule"] != current_molecule:
            current_molecule = run["molecule"]
            lines.extend([
                "",
                f"## {run['molecule']} ({run['dimension']}D)",
            ])
        lines.extend([
            "",
            f"### {run['variant']} — {run['method']}",
            "",
            '<div align="left">',
            "",
            "<table>",
            "<thead>",
            "<tr><th>stage</th><th>interval</th><th>step</th>"
            "<th>ess</th><th>1/sqrt(ess)</th></tr>",
            "</thead>",
            "<tbody>",
        ])
        for stage in run["stages"]:
            interval = f"{stage['t_start']:.6f} → {stage['t']:.6f}"
            for kind, ess in steps([stage]):
                label = (
                    ("identity" if run["method"] == "ID" else "flow")
                    if kind == "selected" else kind
                )
                lines.append(
                    f"<tr><td>{stage['stage']}</td><td>{interval}</td>"
                    f"<td>{label}</td><td>{number(ess)}</td>"
                    f"<td>{number(1.0 / math.sqrt(ess))}</td></tr>"
                )
        lines.extend([
            "</tbody>",
            "</table>",
            "",
            "</div>",
        ])
    return "\n".join(lines) + "\n"


OUTPUT.write_text(build(collect()))
print(OUTPUT)
