import json
import math
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "tables.md"


def number(value):
    return f"{value:.6g}"


def uses_sharpening(stage):
    return stage["rg_start"] != stage["rg_end"]


def collect():
    runs = []
    for molecule_dir in ROOT.iterdir():
        match = re.fullmatch(r"(.+)_([0-9]+)d", molecule_dir.name)
        if not match:
            continue
        molecule = match.group(1).replace("_", " ").title()
        dimension = int(match.group(2))
        for run_file in (molecule_dir / "artifacts").glob("*/run.json"):
            run = json.loads(run_file.read_text())
            method = run["config"].get("method", run_file.parent.name)
            stages = []
            for stage_file in run_file.parent.glob("stages/stage_*/stage.json"):
                stages.append(json.loads(stage_file.read_text()))
            stages.sort(key=lambda stage: stage["stage"])
            if stages:
                runs.append({
                    "molecule": molecule,
                    "dimension": dimension,
                    "method": method.upper(),
                    "status": run["status"],
                    "stages": stages,
                })
    return sorted(
        runs,
        key=lambda run: (run["dimension"], run["method"]),
    )


def factors(stages):
    flow = math.prod(1.0 / stage["valid_selected_ess"] for stage in stages)
    sharpened = [stage for stage in stages if uses_sharpening(stage)]
    sharpening = (
        math.prod(1.0 / stage["sharpen_ess"] for stage in sharpened)
        if sharpened else None
    )
    return flow, sharpening, flow * (sharpening or 1.0)


def build(runs):
    lines = [
        "# Alkane-family ESS tables",
        "",
        "Generated by `python build_table.py` from the accepted-stage metadata in "
        "each molecule's `artifacts` directory.",
        "",
        "Each stage contributes a flow ESS. A sharpening ESS is included only "
        "when that stage changes the regularization parameters. The cumulative "
        "factor is",
        "",
        r"$$\prod_s \frac{1}{\operatorname{ESS}_s},$$",
        "",
        "where the product includes every flow step and each sharpening step "
        "that is actually used.",
        "",
        "## Summary",
        "",
        "| Molecule | Dimension | Method | Status | Stages | Flow factor | "
        "Sharpening factor | Total factor |",
        "|:---|---:|:---:|:---:|---:|---:|---:|---:|",
    ]
    for run in runs:
        flow, sharpening, total = factors(run["stages"])
        sharpening_text = number(sharpening) if sharpening is not None else "—"
        lines.append(
            f"| {run['molecule']} | {run['dimension']} | {run['method']} | "
            f"{run['status']} | {len(run['stages'])} | {number(flow)} | "
            f"{sharpening_text} | {number(total)} |"
        )

    current_molecule = None
    for run in runs:
        if run["molecule"] != current_molecule:
            current_molecule = run["molecule"]
            lines.extend([
                "",
                f"## {run['molecule']} ({run['dimension']}D)",
            ])
        lines.extend([
            "",
            f"### {run['method']}",
            "",
            "| Stage | Interval | Step | ESS | 1/ESS | Cumulative factor |",
            "|---:|:---:|:---|---:|---:|---:|",
        ])
        cumulative = 1.0
        for stage in run["stages"]:
            interval = f"{stage['t_start']:.6f} → {stage['t']:.6f}"
            steps = [("Flow", "valid_selected_ess")]
            if uses_sharpening(stage):
                steps.append(("Sharpening", "sharpen_ess"))
            for step, key in steps:
                ess = stage[key]
                inverse = 1.0 / ess
                cumulative *= inverse
                lines.append(
                    f"| {stage['stage']} | {interval} | {step} | "
                    f"{number(ess)} | {number(inverse)} | "
                    f"{number(cumulative)} |"
                )
    if not runs:
        lines.append("| - | - | - | - | - | - | - | - |")
    return "\n".join(lines) + "\n"


OUTPUT.write_text(build(collect()))
print(OUTPUT)
